[[plugin.deps]]
use = "yazi-rs/plugins:git"
rev = "efa4d79"
hash = "5bb0bfab901d3601c370eafdd66edd31"

[[flavor.deps]]
use = "kshawkat/aurora-storm"
rev = "c28b9da"
hash = "857a516312705831dfda438cb99bd2e5"

[[flavor.deps]]
use = "kshawkat/aurora-dawn"
rev = "9f389d6"
hash = "e90f2a40d8c2f768d84738657b24ffd5"
