[[plugin.deps]]
use = "yazi-rs/plugins:git"
rev = "ac82af3"
hash = "6849444b7c2df08eace83f3f86fb55a3"

[[flavor.deps]]
use = "956MB/vscode-dark-modern"
rev = "cd60541"
hash = "d1134a80fdf8df043b2497846f137f04"
