tap "adoptopenjdk/openjdk"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "minio/stable"
tap "osx-cross/arm"
tap "osx-cross/avr"
tap "qmk/qmk"
brew "automake"
brew "readline"
brew "sqlite"
brew "awscli"
brew "bash"
brew "bash-completion"
brew "bazaar"
brew "bazel"
brew "libffi"
brew "pcre"
brew "glib"
brew "calc"
brew "libtool"
brew "cask"
brew "clang-format"
brew "docker", link: false
brew "docker-compose"
brew "envoy"
brew "etcd", restart_service: true
brew "gawk"
brew "gdb"
brew "git"
brew "gnu-sed"
brew "googler"
brew "goreleaser"
brew "gradle"
brew "graphviz"
brew "protobuf"
brew "grpc"
brew "grpcurl"
brew "haproxy", restart_service: true
brew "helm"
brew "helm@2"
brew "htop"
brew "imagemagick"
brew "iproute2mac"
brew "jq"
brew "k3d"
brew "zookeeper", restart_service: true
brew "kafka", restart_service: true
brew "kubernetes-cli"
brew "minikube"
brew "nginx", restart_service: true
brew "ninja"
brew "nnn"
brew "nuget"
brew "openconnect"
brew "openvpn", restart_service: true
brew "parallel"
brew "pidof"
brew "postgresql", restart_service: true
brew "prototool"
brew "psutils"
brew "python@3.7"
brew "python@3.8"
brew "redis", restart_service: true
brew "ruby"
brew "s3cmd"
brew "shtool"
brew "sl"
brew "speedtest-cli"
brew "telnet"
brew "tree"
brew "upx"
brew "vault", restart_service: true
brew "watch"
brew "wget"
brew "minio/stable/mc"
brew "minio/stable/minio"
brew "qmk/qmk/qmk"
cask "adoptopenjdk"
cask "adoptopenjdk14"
cask "docker"
cask "osxfuse"
cask "wireshark"
