player=mpv
player-passthrough=hls
twitch-supported-codecs=h265,av1,h264
default-stream=best
twitch-api-header=Authorization=OAuth {{ include ".chezmoitemplates/secrets/twitch-auth-token.age" | decrypt | trim }}
