unqualified-search-registries = ["docker.io"]
short-name-mode = "enforcing"

[[registry]]
location = "localhost:5001"
insecure = true

[[registry]]
prefix = "docker.io"
location = "docker.io"

[[registry.mirror]]
location = "mirror.gcr.io"

[[registry]]
location = "quay.io"

[[registry]]
location = "ghcr.io"
