code --install-extension bradymholt.pgformatter
code --install-extension bufbuild.vscode-buf
code --install-extension chrisjsewell.myst-tml-syntax
code --install-extension dakara.transformer
code --install-extension davidanson.vscode-markdownlint
code --install-extension eamodio.gitlens
code --install-extension golang.go
code --install-extension huntertran.auto-markdown-toc
code --install-extension jeff-hykin.better-cpp-syntax
code --install-extension lextudio.restructuredtext
code --install-extension mads-hartmann.bash-ide-vscode
code --install-extension manuth.markdown-converter
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-python.debugpy
code --install-extension ms-python.isort
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-vscode.cpptools
code --install-extension redhat.vscode-yaml
code --install-extension swyddfa.esbonio
code --install-extension trond-snekvik.simple-rst
code --install-extension vintharas.learn-vim
code --install-extension vscodevim.vim
code --install-extension wayou.vscode-todo-highlight
code --install-extension xaver.clang-format
code --install-extension zxh404.vscode-proto3
