#!/usr/bin/env bash

code --install-extension 13xforever.language-x86-64-assembly
code --install-extension adamprzybylski.paradox-syntax
code --install-extension bmarkovic.haproxy
code --install-extension bradymholt.pgformatter
code --install-extension bufbuild.vscode-buf
code --install-extension bungcip.better-toml
code --install-extension dakara.transformer
code --install-extension DavidAnson.vscode-markdownlint
code --install-extension dracula-theme.theme-dracula
code --install-extension eamodio.gitlens
code --install-extension EditorConfig.EditorConfig
code --install-extension golang.go
code --install-extension jeff-hykin.better-cpp-syntax
code --install-extension mads-hartmann.bash-ide-vscode
code --install-extension manuth.markdown-converter
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-dotnettools.csharp
code --install-extension ms-kubernetes-tools.vscode-kubernetes-tools
code --install-extension ms-mssql.mssql
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-toolsai.jupyter
code --install-extension ms-vscode.cpptools
code --install-extension ms-vscode.mono-debug
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension naco-siren.gradle-language
code --install-extension rebornix.ruby
code --install-extension redhat.java
code --install-extension redhat.vscode-commons
code --install-extension redhat.vscode-yaml
code --install-extension shakram02.bash-beautify
code --install-extension SonarSource.sonarlint-vscode
code --install-extension sumneko.lua
code --install-extension tootone.org-mode
code --install-extension twxs.cmake
code --install-extension vintharas.learn-vim
code --install-extension vscjava.vscode-java-debug
code --install-extension vscjava.vscode-java-dependency
code --install-extension vscjava.vscode-java-pack
code --install-extension vscjava.vscode-java-test
code --install-extension vscjava.vscode-maven
code --install-extension vscode-icons-team.vscode-icons
code --install-extension vscodevim.vim
code --install-extension wayou.vscode-todo-highlight
code --install-extension wingrunr21.vscode-ruby
code --install-extension xaver.clang-format
code --install-extension zxh404.vscode-proto3
