fs=no
volume=100

ytdl=yes
ytdl-format=bestvideo[height<=1440]+bestaudio/best[height<=1440]
# ytdl-format=bestvideo*+bestaudio/best
# ytdl-raw-options=cookies-from-browser=firefox

vo=gpu-next
profile=high-quality
hwdec=auto

cache=auto
cache-secs=120
demuxer-max-bytes=512MiB
demuxer-max-back-bytes=128MiB

cache-pause=yes
cache-pause-wait=2

# save-position-on-quit=yes
# watch-later-options=start
autofit-larger=90%x90%
